### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by RikeiR** [deafro5/slanted_display_cases#1]
Japanese translation is here..
[slanted_display_cases_1.2.0_ja.zip](https://github.com/deafro5/slanted_display_cases/files/14227811/slanted_display_cases_1.2.0_ja.zip)

**Comment by deafro5** [comment]
Thanks! I will integrate this tomorrow!

I just added support for different wood types. would you be able to help with the Translation for the 1.3.x build? @RikeiR

**Comment by RikeiR** [comment]
Japanese translation for v1.3.1

[slanted_display_cases_1.3.1_ja.zip](https://github.com/deafro5/slanted_display_cases/files/14228423/slanted_display_cases_1.3.1_ja.zip)

**Comment by deafro5** [comment]
All set! Fixed in Release 1.3.2 Available here: https://mods.vintagestory.at/show/mod/8714#showchangelog
